### ISSUE TITLE
Doesn't Log Raid Loot

### ISSUE THREAD

**Issue by BarklessDog** [RinZJ/better-discord-loot-logger#1]
Raid loot is shown as "Special Loot" in the chat box doesn't come up at valuable or collection log message. Therefore it does not get logged. Could this please get a new option for "Special Loot"

Thanks!

**Comment by BarklessDog** [comment]
![Special Loot](https://user-images.githubusercontent.com/106833565/171918216-c6cf6057-7708-4037-a702-bae3208200cd.png)

**Comment by RinZJ** [comment]
Added this in for version 1.1, will need some testing though to confirm it works :)
