### ISSUE TITLE
Multiple discord webhooks

### ISSUE THREAD

**Issue by 7Shinigami7** [RinZJ/better-discord-loot-logger#10]
I was wondering if it is possible to make it work for multiple discords sir.
I hope you are having a good day :)

**Comment by RinZJ** [comment]
Theoretically yes but unfortunately it's not something I'm planning on adding at the moment, I'll keep it open though and maybe look into it later

**Comment by Jay1175** [comment]
Similar request, but if you make these changes could you make it possible to send collection log slots vs high value drops to different channels? My server is split on whether they want to see collection log slots but they do all want to see valuable uniques

**Comment by iProdigy** [comment]
@7Shinigami7 @Jay1175 [Dink](https://github.com/pajlads/DinkPlugin) allows multiple webhooks & has a webhook "override" section so different notifiers can ping different channels. (disclaimer: I'm a maintainer of that plugin)
