### ISSUE TITLE
Raids Loot Question/Issue

### ISSUE THREAD

**Issue by MJensen03** [RinZJ/better-discord-loot-logger#12]
A couple of buddies were messing around with how the plugin works and they noticed when they disable the chat window, the posts from Chambers of Xeric don't get posted to the discord channel.  We started wondering of why it didn't work on that occasion so I opened up your Github and noticed that you did have an onWidgetLoaded function checking for Chambers.  To my understanding this should have the ability to take the screenshot and post when the Chambers reward chest is opened and post that to the discord channel.  Is this an issue or is there something going on that is intended and I am misunderstanding your code? I'm not full familiar with the Runelite API.

**Comment by RinZJ** [comment]
So the onWidgetLoaded event is only being used to trigger the message but it still requires the chat to actually get the loot info for the message.
