### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by Krikkos** [RinZJ/better-discord-loot-logger#14]
1) Excuse me but can you specify what custom field title and custom field value is supposed to be?
2) Is there a way to filter or whitelist items?
3) The plugin is currently not sending any screenshots to the discord if the rarity or the clan event box is enabled

**Comment by RinZJ** [comment]
1. I'm not sure what you mean by this? Guessing you have the wrong plugin repo though based on number 3
2. There is however I have no plans to add this in at the moment, maybe I will in the future but no guarantees
3. The plugin has never had a clan event box, I'm guessing you are in the wrong plugin repo? Let me know how you got here.
