### ISSUE TITLE
Bingo events

### ISSUE THREAD

**Issue by ItsVendum** [RinZJ/better-discord-loot-logger#15]
Hey I just installed your plugin and the webhook look neat indeed!

Is there a way for an event moderator to whitelist specific drops/achievements for whitelisted players? This would be great for all kinds of events, bingos for example. 

Thanks in advance.

**Comment by RinZJ** [comment]
There isn't at the moment, I'm not actively working on the plugin/playing the game at the moment either so there probably won't be anytime soon. I think there are other plugins out there that do this though.
