### ISSUE TITLE
Coll Log Posts, Value Drops Do Not Post

### ISSUE THREAD

**Issue by spikin2** [RinZJ/better-discord-loot-logger#18]
![image](https://user-images.githubusercontent.com/57685577/224527347-584bb255-ea63-4f2e-8940-de3a28f2bcab.png)
Here are my settings.
Other members in the discord are having their posted. No issues.
I am however unable to get my "Valuable Drops" posted in discord.

New Collection Logs are posting.

**Comment by Kingofspaed** [comment]
I had the same issue and I found the solution. You most likely do not have the valuable loot chat active in your Runescape settings (not Runelite). Search for "drop" in your settings and make sure you activate the following settings: Loot drop notifications and set a minimum threshold (you will be prompted when checking the previous setting). Hope this helps!
![Capture](https://github.com/RinZJ/better-discord-loot-logger/assets/37885793/bb96563a-c6c5-4b2a-a283-4475d603c006)
