### ISSUE TITLE
Working with multiple different discord servers?

### ISSUE THREAD

**Issue by kemppainenjanne** [RinZJ/better-discord-loot-logger#19]
Is it possible to make this use multiple discord webhooks to post loot into multiple different servers?

**Comment by RinZJ** [comment]
Fixed with [[#20 ](https://github.com/RinZJ/better-discord-loot-logger/commit/f60e6bde6f6c0ef0e98a54d17681dec7e42ffc45)](https://github.com/RinZJ/better-discord-loot-logger/commit/f60e6bde6f6c0ef0e98a54d17681dec7e42ffc45)

**Comment by kemppainenjanne** [comment]
If I put 2 webhooks separated by commas, it doest work at all.
My example that DOES NOT work:

> https://discord.com/api/webhooks/1111111111111/asd111asd111asd111, https://discord.com/api/webhooks/2222222222222/asd222asd222asd222

What I am doing wrong?
