### ISSUE TITLE
White List Not Working

### ISSUE THREAD

**Issue by russperlow** [RinZJ/better-discord-loot-logger#24]
I've put names in whitelist, yet other accounts still post

**Comment by iProdigy** [comment]
Are you sure you're reporting this issue to the right plugin repository? I don't see a name allowlist in better discord loot logger's config: https://github.com/RinZJ/better-discord-loot-logger/blob/master/src/main/java/com/betterdiscordlootlogger/BetterDiscordLootLoggerConfig.java

**Comment by russperlow** [comment]
Sorry yeah you can close this. The runelite support page took me here because the plugin was forked from here & I didn't double check
