### ISSUE TITLE
Plugin is no longer on Plugin Hub?

### ISSUE THREAD

**Issue by BarklessDog** [RinZJ/better-discord-loot-logger#4]
Any clue why?

**Comment by BossHuso** [comment]
@BarklessDog @oliverpatrick this plugin shouldn't be in the hub in the first place. Use https://github.com/BossHuso/discord-rare-drop-notificater instead. It's the first plugin that existed and has the most option + is actively maintained. Has far more installs as well.

**Comment by Steabag** [comment]
@BossHuso That one doesn't include collection log drops and pets though

**Comment by BossHuso** [comment]
> @BossHuso That one doesn't include collection log drops and pets though
Create an issue / feature request and we will add it asap :)

**Comment by RinZJ** [comment]
Should be back on there now, will be removing it for good though if/when the collection log feature is added to any of the other discord plugins.

**Comment by oliverpatrick** [comment]
@RinZJ Tbf, I did jimmyrig your changes into discord-notifications. I posted a pull request here: https://github.com/cepawiel/RuneLite-Discord-Notifications/pull/1
