### ISSUE TITLE
Pet Notify Missing space in string concatenate 

### ISSUE THREAD

**Issue by PJGJ210** [RinZJ/better-discord-loot-logger#9]
See below pet gained notify

![image](https://user-images.githubusercontent.com/16944807/179423696-59b60e1a-754f-4667-9ade-dce7ba056c2a.png)

**Comment by RinZJ** [comment]
Fixed with https://github.com/RinZJ/better-discord-loot-logger/commit/27933a07b24e7c317d38041a5f33916819ce870b
